### ISSUE TITLE
Should bootstrap script install foreman?

### ISSUE THREAD

**Issue by CristinaRO** [dxw/project_wisdom#16]
Trying to run the server without `foreman` instructs you to install that gem.

Shouldn't this be part of the bootstrap script?

There might be something I'm missing, which is why I'm making this a question and not a PR. ;)

**Comment by pezholio** [comment]
Ha, no, you're quite right. I think I missed that bit out when @jacksonj04 suggested using the Scripts To Rule Them All pattern 👍
